alias myip="curl icanhazip.com"
alias airport="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
alias bundle="nocorrect bundle"
alias gist="gist --private"
alias spring="nocorrect spring"
alias rspec="nocorrect rspec"
alias cask="brew cask"
alias cap="nocorrect cap"
